-- 禁用 RLS 以导入数据
ALTER TABLE public."Ingredient" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."RecipeTag" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."Recipe" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."Recipe-Ingredient_Map" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."Recipe-Tag_Map" DISABLE ROW LEVEL SECURITY;
